### ISSUE TITLE
Create Terms and conditions page

### ISSUE THREAD

**Issue by NandanVyas** [NandanVyas/bookstore#12]
Create Terms and conditions page

The page should contain be responsive and match the theme.

**Comment by jsvigneshkanna** [comment]
Hi @NandanVyas ,
I would like to work on this issue.

Can you please share the content that has to be in these 3 pages as a draft?

Please assign this issue to my name.
Appreciate that!

**Comment by NandanVyas** [comment]
Sure you can work on it @jsvigneshkanna.
Since this is just a demo project created by me hence you can use any template or sample content that you find fit for these pages.

**Comment by jsvigneshkanna** [comment]
Thank you @NandanVyas  will do it

**Comment by Shouryan** [comment]
hi i would like to work on this... please assign it to me

**Comment by NandanVyas** [comment]
Assigning this to you @Shouryan.
