### ISSUE TITLE
Create Ask a question feature

### ISSUE THREAD

**Issue by NandanVyas** [NandanVyas/bookstore#13]
Create ask a question feature under the Faq section on the home page.

- On submitting, the question and the name of the user must be entered into the database.
- The questions without an answer must not be displayed on the FAQ
- Responsive and matches the theme.
- (Optional) If you can add an upvote feature or something to sort the questions.

**Comment by VaishantMakan** [comment]
Hi @NandanVyas,
I would like to work on this issue.

Please assign this issue to my name.
Appreciate that!

**Comment by NandanVyas** [comment]
Sure.
