### ISSUE TITLE
Fix Contact Us page

### ISSUE THREAD

**Issue by NandanVyas** [NandanVyas/bookstore#21]
Fix the error in the name field.

"Your Name" should be initially like "your email".

 <img src="https://user-images.githubusercontent.com/57463564/196778265-9587a9b8-1215-4ce0-96cf-8a577760db7e.png" alt="Bug" width="500">

**Comment by DragnEmperor** [comment]
@NandanVyas I think I can solve this. Please assign it to me.

**Comment by NandanVyas** [comment]
ok @DragnEmperor
