### ISSUE TITLE
Remove Name and Email from add query (question)

### ISSUE THREAD

**Issue by NandanVyas** [NandanVyas/bookstore#23]
The name and email are useless to us since a user can only submit a question when he/she is logged in.

- [x] Remove the Name and Email fields from the add query page.
- [ ] User must be logged in to add the query.
- [x] Name must be received from the user details.

**Comment by Kishore-abhimanyu** [comment]
Can you assign me this issue?

**Comment by DragnEmperor** [comment]
@NandanVyas this would a great addition to my contributions. Please assign it to me.

**Comment by NandanVyas** [comment]
Sure you can @Kishore-abhimanyu.

Sorry @DragnEmperor, Since @Kishore-abhimanyu has already done the work I can't assign you this. You can create a mechanism to send the user to the login page if he is not logged in from the same button. If you want to work on this I can assign you that. Thanks to both of you.

**Comment by DragnEmperor** [comment]
yes works for me

**Comment by NandanVyas** [comment]
Ok fine.
