### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by NandanVyas** [NandanVyas/bookstore#3]
A README is often the first item a visitor will see when visiting your repository. README files typically include information on:

- What the project does.
- Why the project is useful.
- How users can get started with the project.
- Where users can get help with your project.
- Who maintains and contributes to the project.
- Anything else you might like to add.

**Comment by VaishantMakan** [comment]
Hi! I would like to work on this. Can you please assign this to me?

**Comment by NandanVyas** [comment]
Sure, go ahead.

**Comment by varunsood2003** [comment]
Hey I'm new to open source contribution but would love to work and learn with you can you assign me a issue ?

**Comment by NandanVyas** [comment]
> Hey I'm new to open-source contribution but would love to work and learn with you can you assign me a issue?

Hi @varunsood2003. Sure. There is already an [Issue #12](https://github.com/NandanVyas/bookstore/issues/12) that you can work on. Let me know if you want to work on this or anything else. 
You can create your own issue as well, if I find that your PR will improve the project in any way I will gladly accept it.
