### ISSUE TITLE
As a user an update would be needed in my mail when a new book is added.

### ISSUE THREAD

**Issue by Munnachienyi** [NandanVyas/bookstore#4]
this is a bookstore that would be updated often if I don't find a book firsthand, I would love to receive a mail when new books are added.  
here is what i mean,

![email](https://user-images.githubusercontent.com/105428107/194620474-3b0ae20f-0222-44b8-8216-50560f2f4c9e.png)

**Comment by NandanVyas** [comment]
### Can you please elaborate on the issue?

- In what way do you seek to improve or change the footer?

And on the part of the index.html, since the project uses NEXT JS it has pages as `.js`, `.jsx`, .`ts`, or `.tsx`. 
You can read more about it at https://nextjs.org/docs/basic-features/pages

**Comment by Munnachienyi** [comment]
I would say it isn't aligned correctly, it needs a call to action

**Comment by NandanVyas** [comment]
Yeah sure, you can work on it.

**Comment by Munnachienyi** [comment]
sure

**Comment by NandanVyas** [comment]
Closing this for now. Feel free to reopen.
