### ISSUE TITLE
[Bug] Accordion arrow rotate on toggle

### ISSUE THREAD

**Issue by mitpancholi98** [NandanVyas/bookstore#6]
### Description and reproduction

- In home page, scroll down to FAQ section
- Open one of the faq

### Issue
- When faq is open arrow should be rotated indicating open state.
- Currently accordion expands

 ### Additional Details
- Chrome browser version - 106.0.5249.103

### Screenshots
![image](https://user-images.githubusercontent.com/51367069/194478837-c89eca95-15b1-4e4a-a119-f9192323e6a7.png)
![image](https://user-images.githubusercontent.com/51367069/194478869-8774a7d0-6050-4c8f-88b9-82bf91af839d.png)

**Comment by mitpancholi98** [comment]
Hi can I work this out ?

**Comment by NandanVyas** [comment]
Yeah, sure

**Comment by mitpancholi98** [comment]
Sure

**Comment by VaishantMakan** [comment]
Hi! I would like to work on this if it is open.

**Comment by NandanVyas** [comment]
Yeah sure, since @mitpancholi98 has unassigned himself.
