### ISSUE TITLE
npm run dev not working 

### ISSUE THREAD

**Issue by VaishantMakan** [NandanVyas/bookstore#8]
### Explain the bug and WHERE you saw it (the page, section on the page):
I was not able to run the project locally on my system since the `npm run dev` command failed to execute. 

### Explain what you expected to happen:
Successfully run the project locally on my system. 

### How can we reproduce the bug?
run the command `npm run dev`

### Note your browser and device:
browser: Google Chrome, version: 105.0.5195.125
device: Macbook Pro Intel, MacOS: 12.1

### Would be great if you can share a screenshot or recording!
<img width="528" alt="image" src="https://user-images.githubusercontent.com/56248007/194515038-d784e4ce-e538-4eb9-8182-33a1e4112b56.png">

**Comment by NandanVyas** [comment]
All the required dependencies are present in the package.json file.

![image](https://user-images.githubusercontent.com/57463564/194520128-54427604-cd07-4fff-bd3c-e299929815e7.png)

You just need to install the packages into your local device using the `npm install` command.
You can refer to [this video](https://www.youtube.com/watch?v=i8KuDon82KM&t=135s&ab_channel=h3webdevtuts).

I am closing this issue but feel free to reopen it or contact me if you need any other help.

**Comment by VaishantMakan** [comment]
> All the required dependencies are present in the package.json file.
> 
> ![image](https://user-images.githubusercontent.com/57463564/194520128-54427604-cd07-4fff-bd3c-e299929815e7.png)
> 
> You just need to install the packages into your local device using the `npm install` command. You can refer to [this video](https://www.youtube.com/watch?v=_ynMa2XlRgk&ab_channel=TechProjects).
> 
> I am closing this issue but feel free to reopen it or contact me if you need any other help.

Oh Okay. I understand now.
